/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */




#include <stdint.h>

#define GPIOA_BASEADDR      0x40010800U
#define RCC_BASEADDR        0x40021000U

// Offset thanh ghi
#define RCC_APB2ENR_OFFSET  0x18U
#define GPIO_CRH_OFFSET     0x04U
#define GPIO_ODR_OFFSET     0x0CU


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void SetClockForGPIOA()
{
	int a = 5; //tạo biến a
	int *p;    // tạo con trỏ p
	p = &a;    // trỏ p đến địa chỉ a
	*p = 20;   // thay đổi giá trị của a


	// tạo con trỏ
	uint32_t *ptrToAPB2ENRReg;
	// trỏ tới địa chỉ cần thay đổi
	ptrToAPB2ENRReg = (0x40021000 + 0x18);
	// thay đổi giá trị thanh ghi apb2enr
	*ptrToAPB2ENRReg |=  (1<<3);
}

void delay(void)
{
    for(uint32_t i = 0 ; i < 500000 ; i ++);
}

int main(void)
{
    SetClockForGPIOA();
    uint32_t *ptr;
    // Set bit GPIO B cho pin12
    ptr = (0x40010C00 + 0x04);
    *ptr = 0x10000;

    // Set output cho pin12
    ptr = (0x40010C00 + 0x0C);
    *ptr |= (1<<12);

    while(1)
    {
    	ptr = (0x40010C00 + 0x0C);
    	*ptr &= (0<<12);
    	delay();

    	ptr = (0x40010C00 + 0x0C);
    	*ptr |= (1<<12);
    	delay();
    }

    return 0;
}
