/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

void delay(void)
{
    for(uint32_t i = 0 ; i < 500000 ; i ++);
}

void SetClockForGPIOB()
{
	// tạo con trỏ
	uint32_t *ptrToAPB2ENRReg;
	// trỏ tới địa chỉ cần thay đổi
	ptrToAPB2ENRReg = (0x40021000 + 0x18);
	// thay đổi giá trị thanh ghi apb2enr
	*ptrToAPB2ENRReg |=  (1<<3);
}

void SetClockForGPIOC()
{
	// tạo con trỏ
	uint32_t *ptrToAPB2ENRReg;
	// trỏ tới địa chỉ cần thay đổi
	ptrToAPB2ENRReg = (0x40021000 + 0x18);
	// thay đổi giá trị thanh ghi apb2enr
	*ptrToAPB2ENRReg |=  (1<<4);
}

int main(void)
{
	uint32_t *GPIOB_ODR;
	uint32_t *GPIOC_IDR;
	//Set clock cho GPIO B và GPIO C
	SetClockForGPIOB();
	SetClockForGPIOC();

	//LED
	uint32_t *ptr;
	//Config pin12
	ptr = (0x40010C00 + 0x04);
	*ptr &= ~(0xF<<16);
	*ptr |= (0x1<<16);
	// Set output cho pin12
	GPIOB_ODR = (0x40010C00 + 0x0C); // đc output reg gpioB


	//Button PC15
	//Config pin15
	ptr = (0x40011000 + 0x04);
	*ptr &= ~(0xF<<28);
	*ptr |= (0x8<<28);
	// Set input cho pin15
	GPIOC_IDR = (0x40011000 + 0x08); // đc input reg gpioC

	// Set pullup cho pin15
	uint32_t *GPIOC_ODR;
	GPIOC_ODR = (0x40011000 + 0x0C);
	*GPIOC_ODR |= (1<<15);

	while(1)
	{
		if (((*GPIOC_IDR) & (1<<15)) == 0)
		{
			*GPIOB_ODR |= (1<<12);
		}
		else
		{
			*GPIOB_ODR &= ~(1<<12);
		}
	}

	return 0;
}




